services:
  fm_fastapi_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  fm_fastapi_app:
    image: fm_fastapi_app
    build: .
    entrypoint: /app/entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - fm_fastapi_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@fm_fastapi_database:5432/app_db


volumes:
  pgdata: